module.exports = {
  FETCH_PRODUCTS: "[FETCH_PRODUCT]",
  FETCH_CART: "[FETCH_CART]",
  HANDLE_CART_ADD: "[ADD_TO_CART]",
  HANDLE_CART_UPDATE_QTY: "[UPDATE_QTY]",
  HANDLE_CART_REMOVE_ITEM: "[REMOVE_ITEM]",
  HANDLE_CART_EMPTY: "[EMPTY_CART]",
  GET_TOKEN: "[GET_TOKEN]",
  HANDLE_ORDER: "[HANDLE_ORDER]",
  REFRESH_CART: "[REFRESH_CART]",
};
